web:
  build: ./
  ports:
   - "5000:5000"
  environment:
    - FLASK_APP=server.py
    - FLASK_DEBUG=1
  volumes:
   - .:/app
  links:
    - postgres:postgres
postgres:
  restart: always
  image: postgres:latest
  env_file: .env
  ports:
    - "5432:5432"