web:
  build: ./
  restart: always
  ports:
   - "5000:5000"
  environment:
    - APP_SETTINGS=config.DevelopmentConfig
    - DATABASE_URL=postgresql://marco:foobarbaz@postgres/testdb
  volumes:
   - .:/app
  links:
    - postgres:postgres
postgres:
  restart: always
  image: postgres:latest
  env_file: .env
  ports:
    - "5432:5432"